# Generated by Django 2.2.1 on 2019-05-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190512_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
